---

region: eu-west-2

metrics:
  - aws_namespace: ECS/ContainerInsights
    aws_metric_name: RunningTaskCount
    aws_dimensions: [ClusterName, ServiceName]

  - aws_namespace: ECS/ContainerInsights
    aws_metric_name: PendingTaskCount
    aws_dimensions: [ClusterName, ServiceName]

  - aws_namespace: ECS/ContainerInsights
    aws_metric_name: DesiredTaskCount
    aws_dimensions: [ClusterName, ServiceName]

  - aws_namespace: AWS/ApplicationELB
    aws_metric_name: HealthyHostCount
    aws_dimensions: [LoadBalancer, AvailabilityZone, TargetGroup]

  - aws_namespace: AWS/ApplicationELB
    aws_metric_name: UnHealthyHostCount
    aws_dimensions: [LoadBalancer, AvailabilityZone, TargetGroup]

  - aws_namespace: AWS/ApplicationELB
    aws_metric_name: RequestCount
    aws_dimensions: [LoadBalancer, AvailabilityZone, TargetGroup]

  - aws_namespace: AWS/ApplicationELB
    aws_metric_name: HTTPCode_ELB_2XX_Count
    aws_dimensions: [LoadBalancer, AvailabilityZone, TargetGroup]

  - aws_namespace: AWS/ApplicationELB
    aws_metric_name: HTTPCode_Target_2XX_Count
    aws_dimensions: [LoadBalancer, AvailabilityZone, TargetGroup]

  - aws_namespace: AWS/ApplicationELB
    aws_metric_name: HTTPCode_ELB_3XX_Count
    aws_dimensions: [LoadBalancer, AvailabilityZone, TargetGroup]

  - aws_namespace: AWS/ApplicationELB
    aws_metric_name: HTTPCode_Target_3XX_Count
    aws_dimensions: [LoadBalancer, AvailabilityZone, TargetGroup]

  - aws_namespace: AWS/ApplicationELB
    aws_metric_name: HTTPCode_ELB_4XX_Count
    aws_dimensions: [LoadBalancer, AvailabilityZone, TargetGroup]

  - aws_namespace: AWS/ApplicationELB
    aws_metric_name: HTTPCode_Target_4XX_Count
    aws_dimensions: [LoadBalancer, AvailabilityZone, TargetGroup]

  - aws_namespace: AWS/ApplicationELB
    aws_metric_name: HTTPCode_ELB_502_Count
    aws_dimensions: [LoadBalancer, AvailabilityZone, TargetGroup]

  - aws_namespace: AWS/ApplicationELB
    aws_metric_name: HTTPCode_Target_502_Count
    aws_dimensions: [LoadBalancer, AvailabilityZone, TargetGroup]

  - aws_namespace: AWS/ApplicationELB
    aws_metric_name: HTTPCode_ELB_504_Count
    aws_dimensions: [LoadBalancer, AvailabilityZone, TargetGroup]

  - aws_namespace: AWS/ApplicationELB
    aws_metric_name: HTTPCode_Target_504_Count
    aws_dimensions: [LoadBalancer, AvailabilityZone, TargetGroup]

  - aws_namespace: AWS/ApplicationELB
    aws_metric_name: HTTPCode_ELB_5XX_Count
    aws_dimensions: [LoadBalancer, AvailabilityZone, TargetGroup]

  - aws_namespace: AWS/ApplicationELB
    aws_metric_name: HTTPCode_Target_5XX_Count
    aws_dimensions: [LoadBalancer, AvailabilityZone, TargetGroup]

  - aws_namespace: AWS/NetworkELB
    aws_metric_name: HealthyHostCount
    aws_dimensions: [LoadBalancer, TargetGroup]

  - aws_namespace: AWS/NetworkELB
    aws_metric_name: UnHealthyHostCount
    aws_dimensions: [LoadBalancer, TargetGroup]

  - aws_namespace: AWS/Lambda
    aws_metric_name: Invocations
    aws_dimensions: [FunctionName]

  - aws_namespace: AWS/Lambda
    aws_metric_name: Errors
    aws_dimensions: [FunctionName]

  - aws_namespace: AWS/ECS
    aws_metric_name: MemoryUtilization
    aws_dimensions: [ClusterName, ServiceName]

  - aws_namespace: AWS/ECS
    aws_metric_name: CPUUtilization
    aws_dimensions: [ClusterName, ServiceName]

  - aws_namespace: ECS/ContainerInsights
    aws_metric_name: RunningTaskCount
    aws_dimensions: [ClusterName, ServiceName]

  - aws_namespace: ECS/ContainerInsights
    aws_metric_name: PendingTaskCount
    aws_dimensions: [ClusterName, ServiceName]

  - aws_namespace: AWS/ES
    aws_metric_name: CPUUtilization
    aws_dimensions: [DomainName, NodeId]

  - aws_namespace: AWS/ES
    aws_metric_name: FreeStorageSpace
    aws_dimensions: [DomainName, NodeId]

  - aws_namespace: AWS/ES
    aws_metric_name: JVMMemoryPressure
    aws_dimensions: [DomainName, NodeId]

  - aws_namespace: AWS/ES
    aws_metric_name: SysMemoryUtilization
    aws_dimensions: [DomainName, NodeId]

  - aws_namespace: AWS/RDS
    aws_metric_name: CPUUtilization
    aws_dimensions: [DBClusterIdentifier]

  - aws_namespace: AWS/RDS
    aws_metric_name: DatabaseConnections
    aws_dimensions: [DBClusterIdentifier]

  - aws_namespace: AWS/RDS
    aws_metric_name: DatabaseConnections
    aws_dimensions: [DBInstanceIdentifier]

  - aws_namespace: AWS/RDS
    aws_metric_name: FreeLocalStorage
    aws_dimensions: [DBClusterIdentifier]

  - aws_namespace: AWS/RDS
    aws_metric_name: VolumeBytesUsed
    aws_dimensions: [DBClusterIdentifier]

  - aws_namespace: AWS/AmazonMQ
    aws_metric_name: CpuUtilization
    aws_dimensions: [Broker]

  - aws_namespace: AWS/AmazonMQ
    aws_metric_name: TotalMessageCount
    aws_dimensions: [Broker]

  - aws_namespace: AWS/AmazonMQ
    aws_metric_name: TotalConsumerCount
    aws_dimensions: [Broker]

  - aws_namespace: AWS/AmazonMQ
    aws_metric_name: TotalProducerCount
    aws_dimensions: [Broker]

  - aws_namespace: AWS/AmazonMQ
    aws_metric_name: TotalEnqueueCount
    aws_dimensions: [Broker]

  - aws_namespace: AWS/AmazonMQ
    aws_metric_name: TotalDequeueCount
    aws_dimensions: [Broker]

  - aws_namespace: AWS/AmazonMQ
    aws_metric_name: ProducerCount
    aws_dimensions: [Broker, Topic]

  - aws_namespace: AWS/AmazonMQ
    aws_metric_name: ConsumerCount
    aws_dimensions: [Broker, Topic]

  - aws_namespace: AWS/AmazonMQ
    aws_metric_name: InFlightCount
    aws_dimensions: [Broker, Topic]

  - aws_namespace: AWS/AmazonMQ
    aws_metric_name: MemoryUsage
    aws_dimensions: [Broker, Topic]

  # Broker,Queue metrics to graph our message rates
  - aws_namespace: AWS/AmazonMQ
    aws_metric_name: DispatchCount
    aws_dimensions: [Broker, Queue]

  - aws_namespace: AWS/AmazonMQ
    aws_metric_name: ProducerCount
    aws_dimensions: [Broker, Queue]

  - aws_namespace: AWS/AmazonMQ
    aws_metric_name: DequeueCount
    aws_dimensions: [Broker, Queue]

  - aws_namespace: AWS/AmazonMQ
    aws_metric_name: EnqueueCount
    aws_dimensions: [Broker, Queue]

  - aws_namespace: AWS/AmazonMQ
    aws_metric_name: InFlightCount
    aws_dimensions: [Broker, Queue]

  - aws_namespace: AWS/AmazonMQ
    aws_metric_name: MemoryUsage
    aws_dimensions: [Broker, Queue]

  - aws_namespace: AWS/AmazonMQ
    aws_metric_name: EnqueueTime
    aws_dimensions: [Broker, Queue]

  - aws_namespace: AWS/AmazonMQ
    aws_metric_name: ExpiredCount
    aws_dimensions: [Broker, Queue]

  - aws_namespace: AWS/AmazonMQ
    aws_metric_name: ConsumerCount
    aws_dimensions: [Broker, Queue]

  - aws_namespace: AWS/AmazonMQ
    aws_metric_name: QueueSize
    aws_dimensions: [Broker, Queue]

  # yamllint disable rule:line-length
  # S3 Storage metrics are published to Cloudwatch 1x per day with a timestamp of midnight UTC, hence period_seconds: 86400
  # Publishing does not always occur at the same time, but it will occur before the next day, hence range_seconds: 172800
  # Valid statistics (https://docs.aws.amazon.com/AmazonS3/latest/dev/cloudwatch-monitoring.html): Average
  # yamllint enable rule:line-length
  - aws_namespace: AWS/S3
    aws_metric_name: BucketSizeBytes
    aws_dimensions: [BucketName, StorageType]
    aws_statistics: [Average]
    range_seconds: 172800
    period_seconds: 86400

  - aws_namespace: AWS/S3
    aws_metric_name: NumberOfObjects
    aws_dimensions: [BucketName, StorageType]
    aws_statistics: [Average]
    range_seconds: 172800
    period_seconds: 86400

  - aws_namespace: AWS/States
    aws_metric_name: ExecutionsFailed
    aws_dimensions: [StateMachineArn]

  - aws_namespace: AWS/States
    aws_metric_name: ExecutionsTimedOut
    aws_dimensions: [StateMachineArn]

  - aws_namespace: AWS/States
    aws_metric_name: ExecutionsAborted
    aws_dimensions: [StateMachineArn]

  - aws_namespace: AWS/States
    aws_metric_name: ExecutionThrottled
    aws_dimensions: [StateMachineArn]
...
