version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/Amazon_Linux_2023_Base/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/Liquibase/"
    schedule:
      interval: "daily"
