---
version: 0.2

env:
  variables:
    GOSS_RETRY_TIMEOUT: "120s"
  exported-variables:
    - CONDUCTOR_IMAGE_HASH

phases:
  build:
    commands:
      - set -ev
      - cd Conductor
      - /bin/bash ./scripts/build_docker.sh
