---

version: 0.2

env:
  exported-variables:
    - CONDUCTOR_IMAGE_HASH

phases:
  build:
    commands:
      - set -ev
      - cd Conductor
      - /bin/bash ./scripts/download_and_patch_conductor.sh
      - /bin/bash ./scripts/build_docker.sh
...
