---
version: 0.2

env:
  exported-variables:
    - CONDUCTOR_IMAGE_HASH

phases:
  build:
    commands:
      - set -ev
      - docker version
      - cd Conductor
      - /bin/bash ./scripts/build_docker.sh
