version: '3'
services:
  elasticsearch:
    image: opensearchproject/opensearch
    container_name: elasticsearch
    environment:
      - node.name=ws-es-node
      - discovery.type=single-node
      - cluster.name=ws-es-data-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - logger.level=debug
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
      - 9600:9600
    networks:
      - esnet
  kibana:
    image: opensearchproject/opensearch-dashboards
    container_name: kibana
    environment:
      SERVER_NAME: kibana
      OPENSEARCH_HOSTS: https://elasticsearch:9200
    ports:
      - 5601:5601
    expose:
      - 5601
    networks:
      - esnet
    depends_on:
      - elasticsearch
    restart: "unless-stopped"

  logstash:
    image: logstash
    container_name: logstash
    env_file:
      - goss.env
    networks:
      - esnet
    depends_on:
      - elasticsearch
    restart: "unless-stopped"
    volumes:
     - ./logstash_conf:/etc/logstash/conf.d

volumes:
  esdata:
    driver: local

networks:
  esnet:
