file:
  /certs:
    exists: true
    owner: root
    group: root
    filetype: directory
  /certs/server.crt:
    exists: true
    owner: root
    group: root
    filetype: file
  /certs/server.key:
    exists: true
    owner: root
    group: root
    filetype: file
  /config/config.yml:
    exists: true
    owner: root
    group: root
    filetype: file
  /etc/nginx/nginx.conf:
    exists: true
    owner: root
    group: root
    filetype: file
    contains: []
  /etc/passwd:
    exists: true
    mode: "0644"
    owner: root
    group: root
    filetype: file
  /etc/supervisord.conf:
    exists: true
    owner: root
    group: root
    filetype: file
  /tmp/install_blackbox_exporter.sh:
    exists: false
  /tmp/openssl.cnf:
    exists: false
package:
  deltarpm:
    installed: true
  epel-release:
    installed: true
  nginx:
    installed: true
  python:
    installed: true
  python2-pip:
    installed: true
  shadow-utils:
    installed: true
port:
  tcp:80:
    listening: false
  tcp:443:
    listening: false
  tcp:9001:
    listening: true
    ip:
    - 127.0.0.1
  tcp:9116:
    listening: true
    ip:
    - 0.0.0.0
user:
  dbus:
    exists: true
    uid: 81
    gid: 81
    groups:
    - dbus
    home: /
    shell: /sbin/nologin
  nginx:
    exists: true
    uid: 999
    gid: 998
    groups:
    - nginx
    home: /var/lib/nginx
    shell: /sbin/nologin
  nobody:
    exists: true
    uid: 99
    gid: 99
    groups:
    - nobody
    home: /
    shell: /sbin/nologin
  systemd-network:
    exists: true
    uid: 192
    gid: 192
    groups:
    - systemd-network
    home: /
    shell: /sbin/nologin
command:
  supervisorctl status:
    exit-status: 0
    stdout:
#    - /cloudwatch_exporter\W+RUNNING\W+pid\W\d{1,},\Wuptime\W\S+/
#    - /cron:crond\W+RUNNING\W+pid\W\d{1,},\Wuptime\W\S+/
    - /nginx\W+RUNNING\W+pid\W\d{1,},\Wuptime\W\S+/
    timeout: 10000
process:
  nginx:
    running: true
  supervisord:
    running: true
