{
 "title": "Bichard7 QSolution",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Bichard Container Status",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecs_containerinsights_desired_task_count_sum{service_name=\"cjse-bichard7-qsolution-base-infra\"}",
     "legendFormat": "Desired Containers"
    },
    {
     "expr": "ecs_containerinsights_running_task_count_sum{service_name=\"cjse-bichard7-qsolution-base-infra\"}",
     "legendFormat": "Running Containers"
    },
    {
     "expr": "aws_applicationelb_healthy_host_count_average{availability_zone=~\"eu-west-2a|eu-west-2b|eu-west-2c\",target_group=\"targetgroup/b7app20210623152452436800000002/f8557a55f5d74100\"}",
     "legendFormat": "Healthy Hosts {{availability_zone}}"
    }
   ]
  },
  {
   "title": "Bichard Application ECS Container Metrics",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "aws_ecs_cpuutilization_average{cluster_name=\"cjse-bichard7-qsolution-base-infra\"}",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "aws_ecs_memory_utilization_average{cluster_name=\"cjse-bichard7-qsolution-base-infra\"}",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  {
   "title": "Bichard Queues",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aws_amazonmq_total_producer_count_sum{broker=~\"cjse-qsolution-bichard-7-amq-1|cjse-qsolution-bichard-7-amq-2\"}",
     "legendFormat": "Total Producers"
    },
    {
     "expr": "aws_amazonmq_total_consumer_count_sum{broker=~\"cjse-qsolution-bichard-7-amq-1|cjse-qsolution-bichard-7-amq-2\"}",
     "legendFormat": "Total Consumers"
    },
    {
     "expr": "aws_amazonmq_total_message_count_sum{broker=~\"cjse-qsolution-bichard-7-amq-1|cjse-qsolution-bichard-7-amq-2\"}",
     "legendFormat": "Total Messages {{broker}}"
    },
    {
     "expr": "aws_amazonmq_total_enqueue_count_sum{broker=~\"cjse-qsolution-bichard-7-amq-1|cjse-qsolution-bichard-7-amq-2\"}",
     "legendFormat": "Enqueued Messages"
    },
    {
     "expr": "aws_amazonmq_total_dequeue_count_sum{broker=~\"cjse-qsolution-bichard-7-amq-1|cjse-qsolution-bichard-7-amq-2\"}",
     "legendFormat": "Dequeued Messages"
    }
   ]
  },
  {
   "title": "Bichard DB Metrics",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "aws_rds_cpuutilization_average{dbcluster_identifier=\"cjse-qsolution-bichard-7-aurora-cluster\"}",
     "legendFormat": "CPU Uitilsation {{dbcluster_identifier}}"
    },
    {
     "expr": "aws_rds_database_connections_sum{dbcluster_identifier=\"cjse-qsolution-bichard-7-aurora-cluster\"}",
     "legendFormat": "DB Connections {{dbcluster_identifier}}"
    }
   ]
  },
  {
   "title": "Bichard DB Storage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 9 },
   "targets": [
    {
     "expr": "aws_rds_database_free_local_storage_sum{dbcluster_identifier=\"cjse-qsolution-bichard-7-aurora-cluster\"}",
     "legendFormat": "CPU Uitilsation {{dbcluster_identifier}}"
    },
    {
     "expr": "aws_rds_database_volume_bytes_used_sum{dbcluster_identifier=\"cjse-qsolution-bichard-7-aurora-cluster\"}",
     "legendFormat": "DB Connections {{dbcluster_identifier}}"
    }
   ]
  },
  {
   "title": "Monitoring ECS Container Metrics",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aws_ecs_cpuutilization_average{cluster_name=\"cjse-qsolution-bichard-7-monitoring\"}",
     "legendFormat": "CPU Utilisation {{service_name}}"
    },
    {
     "expr": "aws_ecs_memory_utilization_average{cluster_name=\"cjse-qsolution-bichard-7-monitoring\"}",
     "legendFormat": "Memory Utilisation {{service_name}}"
    }
   ]
  }
 ]
}